### ISSUE TITLE
MartinCostello.SqlLocalDb.SqlLocalDbException : The buffer passed to the LocalDB instance API method has insufficient size.

### ISSUE THREAD

**Issue by Rubenisme** [martincostello/sqllocaldb#991]
## Describe the bug

When we run tests in parallel then we get an exception `MartinCostello.SqlLocalDb.SqlLocalDbException : The buffer passed to the LocalDB instance API method has insufficient size.`

## Steps To reproduce

Run many instances that run `GetInstances` in parallel, when in the meantime new instances can get created and the buffer passed to store the instance names has already been created, this exception occurs.

## Expected behavior

No exception happens

## Actual behavior

Stack trace
at MartinCostello.SqlLocalDb.SqlLocalDbApi.InvokeThrowOnError(Func`1 func, EventId eventId, String instanceName)
at MartinCostello.SqlLocalDb.SqlLocalDbApi.GetInstanceNames()
at MartinCostello.SqlLocalDb.ISqlLocalDbApiExtensions.GetInstances(ISqlLocalDbApi api)
at Shared.TestSupport.Integration.MartinCostelloSqlLocalDbProvider.DeleteExpiredInstances()

## System information
- OS: [e.g. Windows 10]
- Library Version latest
- SQL LocalDB version 2022

## Additional context

We use `DeleteExpiredInstances` after every test, and this calls `var instances = _sqlLocalDbApi.GetInstances();` this is where it fails.

**Comment by martincostello** [comment]
The exception comes from [this method](https://github.com/martincostello/sqllocaldb/blob/d4e272ce2b0d94b7323deb4c55f7b575bc16c2c8/src/SqlLocalDb/SqlLocalDbApi.cs#L592-L631).

I'm not sure how thorough any fix for this can be as it's accessing what's effectively a machine-wide resources, so the number of instances could change at any time. I could make some changes to retry with a bigger buffer (or keep calling in a loop until it works), but I don't think there's a way to make it guaranteed to succeed, short of allocating an overly buffer "just in case".

There's probably scope for a change to me it less likely to fail, but I'm not sure about 100% reliability in the face of this sort of parallelism as getting the names relies of asking the API for the count, and then calling it again with a buffer large enough to get the names. If the number increases between those two calls, the buffer is going to be too small.

Another approach could be to just to ignore the "too small" error and return however many were known about when the first function call was made.

From a pure performance perspective, I would call `DeleteExpiredInstances()` after each test run, rather than each _test_. You're going to slow down your test suite by, from my recollection when I regularly used this library in my own tests, 1-2 seconds per test.

**Comment by martincostello** [comment]
I'm inclined to _not_ make any changes to fix this.

The usage is the same as [the sample code](https://learn.microsoft.com/sql/relational-databases/sql-server-express-localdb-reference#code-sample), so it's not like the library is doing something unusual.

Further, based on the call stack you've given, changing this is just potentially going to lead to a failure elsewhere. For example, here:

https://github.com/martincostello/sqllocaldb/blob/d4e272ce2b0d94b7323deb4c55f7b575bc16c2c8/src/SqlLocalDb/ISqlLocalDbApiExtensions.cs#L67-L78

Once the names are queried, if a parallel operation has caused one of the instances to have been deleted, the [`LocalDBGetInstanceInfo()`](https://learn.microsoft.com/sql/relational-databases/express-localdb-instance-apis/localdbgetinstanceinfo-function) function that gets the instance information will return [`LOCALDB_ERROR_INVALID_INSTANCE_NAME`](https://learn.microsoft.com/sql/relational-databases/express-localdb-error-messages/localdb-error-invalid-instance-name), and then an exception will be thrown, so the `DeleteExpiredInstances()` method will still fail.

Instead, I would recommend you avoid mutating the state of the SQL Server LocalDB Instance API in parallel during your tests, and just do tear-down operations at the end of your test run, rather than after every test.

**Comment by Rubenisme** [comment]
Sorry for getting back to you a bit late, a coworker of mine actually had this instead of me myself, so had to get some details. He used:
```csharp
internal interface ISqlLocalDbProvider
{
    void DeleteExpiredInstances();
    void DeleteInstance();
    void Dispose();
    string StartInstance();
}

internal sealed class MartinCostelloSqlLocalDbProvider : IDisposable, ISqlLocalDbProvider
{
    private readonly SqlLocalDbApi _sqlLocalDbApi;
    private ISqlLocalDbInstanceManager? _sqlLocalDbInstanceManager;
    private ISqlLocalDbInstanceInfo? _sqlLocalDbInstanceInfo;
    private readonly string _instanceNamePrefix;
    private readonly string _instanceName;
    private readonly int _minutesBeforeInstanceExpiration;
    private bool _disposedValue;

    public MartinCostelloSqlLocalDbProvider(string instanceNamePrefix, int minutesBeforeInstanceExpiration)
    {
        _sqlLocalDbApi = new SqlLocalDbApi(
            new()
            {
                AutomaticallyDeleteInstanceFiles = true,
                StopOptions = StopInstanceOptions.NoWait,
                StopTimeout = TimeSpan.FromSeconds(1),
            }, NullLoggerFactory.Instance);
        _minutesBeforeInstanceExpiration = minutesBeforeInstanceExpiration;
        _instanceNamePrefix = instanceNamePrefix;
        _instanceName = GenerateSemiRandomInstanceName(instanceNamePrefix);

        static string GenerateSemiRandomInstanceName(string prefix)
        {
            var randomName = prefix + Guid.NewGuid().ToString("N");
            var maxNameLength = Math.Min(randomName.Length, 50);
            return randomName[..maxNameLength];
        }
    }

    public string StartInstance()
    {
        _sqlLocalDbInstanceInfo = _sqlLocalDbApi.GetOrCreateInstance(_instanceName);
        _sqlLocalDbInstanceManager = _sqlLocalDbInstanceInfo.Manage();

        if (!_sqlLocalDbInstanceInfo.IsRunning)
        {
            _sqlLocalDbInstanceManager.Start();
        }

        return _sqlLocalDbInstanceInfo.GetConnectionString() + ";TrustServerCertificate=true;MultipleActiveResultSets=True";
    }

    public void DeleteExpiredInstances()
    {
        var instances = _sqlLocalDbApi.GetInstances();

        var expiredInstances = instances
            .Where(IsInActiveInstance)
            .Where(IsOwnedInstance)
            .Where(IsExpiredInstance)
            .ToList();

        expiredInstances
            .ForEach(DeleteInstance);

        bool IsExpiredInstance(ISqlLocalDbInstanceInfo instance)
        {
            return instance.LastStartTimeUtc < DateTime.UtcNow.Add(TimeSpan.FromMinutes(-_minutesBeforeInstanceExpiration));
        }

        bool IsInActiveInstance(ISqlLocalDbInstanceInfo instance)
        {
            return instance is { IsRunning: false, IsAutomatic: false, IsShared: false };
        }

        bool IsOwnedInstance(ISqlLocalDbInstanceInfo instance)
        {
            return instance.Name.StartsWith(_instanceNamePrefix) &&
                   instance.Name != _sqlLocalDbApi.DefaultInstanceName;
        }
    }

    public void DeleteInstance()
    {
        if (_sqlLocalDbInstanceInfo is null)
        {
            return;
        }

        try
        {
            _sqlLocalDbApi.StopInstance(_sqlLocalDbInstanceInfo.Name, TimeSpan.FromSeconds(120));
            DeleteInstance(_sqlLocalDbInstanceInfo);
        }
        catch (Exception)
        {
            // ignored, we tried...
        }
    }

    private void DeleteInstance(ISqlLocalDbInstanceInfo instance)
    {
        try
        {
            _sqlLocalDbApi.DeleteInstance(instance.Name);
            Console.WriteLine($"Deleted instance {instance.Name}");
        }
        catch (Exception)
        {
            // ignored
        }
    }

    private void Dispose(bool disposing)
    {
        if (!_disposedValue)
        {
            if (disposing)
            {
                _sqlLocalDbInstanceManager?.Stop();
                DeleteInstance();
                DeleteExpiredInstances();
                var sqlLocalDbApi = _sqlLocalDbApi;
                sqlLocalDbApi?.Dispose();

                // ReSharper disable once RedundantAssignment
                sqlLocalDbApi = null;
            }

            _disposedValue = true;
        }
    }

    public void Dispose()
    {
        // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
}
```

And now "fixed" it by using this instead:
```csharp
internal class OwnSqlLocalDbProvider : ISqlLocalDbProvider, IDisposable
{
    private int _minutesBeforeInstanceExpiration;
    private string _instanceNamePrefix;
    private string _instanceName;
    private string? _owner;
    private SqlLocalDbInstanceInfo? _instance;
    private bool _disposedValue;

    internal OwnSqlLocalDbProvider(string instanceNamePrefix, int minutesBeforeInstanceExpiration)
    {
        _minutesBeforeInstanceExpiration = minutesBeforeInstanceExpiration;
        _instanceNamePrefix = instanceNamePrefix;
        _instanceName = GenerateSemiRandomInstanceName(instanceNamePrefix);

        static string GenerateSemiRandomInstanceName(string prefix)
        {
            var randomName = prefix + Guid.NewGuid().ToString("N");
            var maxNameLength = Math.Min(randomName.Length, 50);
            return randomName[..maxNameLength];
        }
    }

    public void DeleteExpiredInstances()
    {
        var names = SqlLocalDbApi.GetInstanceNames();
        foreach (var name in names)
        {
            // cannot act on instances without a name
            if (string.IsNullOrWhiteSpace(name))
            {
                continue;
            }

            // do not want to delete the default instance
            if(SqlLocalDbApi.IsDefaultInstanceName(name))
            {
                continue;
            }

            var instanceInfo = SqlLocalDbApi.GetInstance(name);

            // do not touch instance if current process user is not the owner of the instance
            if(!string.Equals(instanceInfo.Owner, _owner, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            // let shared or auto-created instances be
            if (instanceInfo.Shared is true || instanceInfo.AutoCreate is true)
            {
                continue;
            }

            // let running instances be unless they have exceeded their expiration limit
            if (instanceInfo.State is SqlLocalDbInstanceState.Running)
            {
                var lastStarted = (DateTime.Now - instanceInfo.LastStartTime);

                // they have not yet exceeded their expiration limit
                if (lastStarted.TotalMinutes < _minutesBeforeInstanceExpiration)
                {
                    continue;
                }

                // stop running instances when they have exceeded their expiration limit
                SqlLocalDbApi.StopInstance(instanceInfo.Name);
            }

            // delete the instance and its files
            var deleteResult = SqlLocalDbApi.DeleteInstance(instanceInfo.Name);
        }
    }

    public void DeleteInstance()
    {
        if(_instance is not null) { 
            SqlLocalDbApi.StopInstance(_instance.Name);
            SqlLocalDbApi.DeleteInstance(_instance.Name);
        }
    }

    public string StartInstance()
    {
        var existingInstances = SqlLocalDbApi.GetInstanceNames();
        if (existingInstances.Contains(_instanceName))
        {
            var instance = SqlLocalDbApi.GetInstance(_instanceName);
            if(instance.State == SqlLocalDbInstanceState.Stopped)
            {
                SqlLocalDbApi.StartInstance(instance.Name);
                // pipe information only gets added after start so get instance info again
                _instance = SqlLocalDbApi.GetInstance(_instanceName);
            }
        }
        else
        {
            var defaultInstance = SqlLocalDbApi.GetInstance(SqlLocalDbApi.DefaultInstanceName2014AndLater);
            SqlLocalDbApi.CreateInstance(_instanceName, defaultInstance.Version, startImmediately: true);
            _instance = SqlLocalDbApi.GetInstance(_instanceName);
        }
        _owner = _instance!.Owner;
        return $"Data Source={_instance.Pipe};TrustServerCertificate=true;MultipleActiveResultSets=True";
    }

    private void Dispose(bool disposing)
    {
        if (!_disposedValue)
        {
            if (disposing)
            {
                DeleteInstance();
                DeleteExpiredInstances();
            }

            _disposedValue = true;
        }
    }

    public void Dispose()
    {
        // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    private sealed class SqlLocalDbApi
    {
        internal const string DefaultInstanceName2012 = "v11.0";
        internal const string DefaultInstanceName2014AndLater = "MSSQLLocalDB";

        internal static string[] GetInstanceNames()
        {
            var outcome = ExecuteProcess("info");
            // Instance1
            // MSSQLLocalDB
            // OtherInstance
            return outcome.Split("\r\n");
        }

        internal static SqlLocalDbInstanceInfo GetInstance(string instanceName)
        {
            var outcome = ExecuteProcess($"info \"{instanceName}\"");
            return ParseInstanceInfo(outcome);
        }

        internal static void CreateInstance(string instanceName, string version, bool startImmediately)
        {
            var startFlag = startImmediately ? " -s" : "";
            var outcome = ExecuteProcess($"create \"{instanceName}\" \"{version}\"{startFlag}");
        }

        internal static void StartInstance(string instanceName)
        {
            var outcome = ExecuteProcess($"start \"{instanceName}\"");
        }

        internal static void StopInstance(string instanceName)
        {
            var outcome = ExecuteProcess($"stop \"{instanceName}\"");
        }

        internal static string DeleteInstance(string instanceName)
        {
            var outcome = ExecuteProcess($"delete \"{instanceName}\"");
            // LocalDB instance "{instanceName}" deleted.
            DeleteInstanceFiles(instanceName);
            return outcome;
        }

        internal static SqlLocalDbInstanceInfo ParseInstanceInfo(string instanceInfo)
        {
            // Name:               MSSQLLocalDB
            // Version:            15.0.4153.1
            // Shared name:
            // Owner:              Domain\WindowsUser
            // Auto-create:        Yes
            // State:              Stopped
            // Last start time:    11-9-2024 10:27:34
            // Instance pipe name: np:\\.\pipe\LOCALDB#D7FFD690\tsql\query

            var rawPropertiesInfo = instanceInfo.Split("\r\n");
            var properties = rawPropertiesInfo
                .Where(propertyInfo => propertyInfo.IndexOf(':') > -1)
                .Select(propertyInfo =>
                {
                    var firstColonIndex = propertyInfo.IndexOf(':');
                    var namePart = propertyInfo.Substring(0, firstColonIndex).Trim();
                    var valuePart = propertyInfo.Substring(firstColonIndex + 1).Trim();

                    return (Name: namePart, Value: valuePart);
                })
                .Where(property => !string.IsNullOrWhiteSpace(property.Name))
                .ToArray();

            return new SqlLocalDbInstanceInfo(
                Name: GetValue(properties, "Name") ?? "",
                Version: GetValue(properties, "Version") ?? "",
                Owner: GetValue(properties, "Owner") ?? "",
                State: ParseState(GetValue(properties, "State")),
                Shared: ParseShared(GetValue(properties, "Shared name")),
                AutoCreate: ParseAutoCreate(GetValue(properties, "Auto-create")),
                LastStartTime: ParseDateTime(GetValue(properties, "Last start time")),
                Pipe: GetValue(properties, "Instance pipe name") ?? ""
            );

            static DateTime ParseDateTime(string? dateTimeString)
            {
                // Last start time:    11-9-2024 10:27:34 [depending on culture]
                if (dateTimeString is null)
                {
                    return DateTime.UnixEpoch;
                }
                return DateTime.Parse(dateTimeString, CultureInfo.CurrentCulture);
            }

            static bool ParseShared(string? value)
            {
                // Shared name:
                if (value is null)
                {
                    return false;
                }
                return !string.IsNullOrWhiteSpace(value);
            }

            static bool ParseAutoCreate(string? value)
            {
                // Auto-create:        Yes
                if (value is null)
                {
                    return false;
                }
                return value != "No";
            }

            static SqlLocalDbInstanceState ParseState(string? value)
            {
                // State:              Stopped
                return value switch
                {
                    "Stopped" => SqlLocalDbInstanceState.Stopped,
                    "Running" => SqlLocalDbInstanceState.Running,
                    _ => SqlLocalDbInstanceState.Unknown
                };
            }

            static string? GetValue((string Name, string Value)[] properties, string name)
            {
                return properties.Where(property => property.Name == name).Select(property => property.Value).FirstOrDefault();
            }
        }

        internal static bool IsDefaultInstanceName(string instanceName)
        {
            return
                string.Equals(instanceName, DefaultInstanceName2014AndLater, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(instanceName, DefaultInstanceName2012, StringComparison.OrdinalIgnoreCase);
        }

        private static string ExecuteProcess(string arguments)
        {
            ProcessStartInfo processStartInfo = new ProcessStartInfo
            {
                FileName = "sqllocaldb",
                Arguments = arguments,
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            // Start the process
            using (Process process = new Process())
            {
                process.StartInfo = processStartInfo;
                process.Start();

                // Read the output
                string output = process.StandardOutput.ReadToEnd();
                process.WaitForExit();
                Console.WriteLine($"sqllocaldb {arguments}");
                Console.WriteLine("");
                Console.WriteLine(output);

                return output;
            }
        }

        private static void DeleteInstanceFiles(string instanceName)
        {
            // Sanitize the instance name's path to prevent directory traversal
            string instanceNameSafe = Path.GetFullPath(instanceName);
            instanceNameSafe = Path.GetFileName(instanceNameSafe);

            string instancePath = Path.Combine(GetInstancesFolderPath(), instanceNameSafe);

            if (Directory.Exists(instancePath))
            {
                Directory.Delete(instancePath, recursive: true);
            }
        }

        private static string GetInstancesFolderPath()
        {
            return Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "Microsoft",
                "Microsoft SQL Server Local DB",
                "Instances");
        }

    }

    private sealed record SqlLocalDbInstanceInfo(
        string Name,
        string Version,
        string Owner,
        SqlLocalDbInstanceState State,
        bool Shared,
        bool AutoCreate,
        DateTime LastStartTime,
        string Pipe
    );

    private enum SqlLocalDbInstanceState
    {
        Unknown,
        Stopped,
        Running
    }
}
```

I agree that it would be best to do a tear-down at the end of the test run instead but that runs the risk of users cancelling builds and not getting cleaned up. In any case we could also do a try/catch around the `GetInstances`. Thanks for your help and thoughts.
